server:
   port: 7000
   tomcat:
      max-threads: 100
      uri-encoding: UTF-8
spring:
   application:
      name: business-provider-gateway
   cloud:
      gateway:
         routes:
           - id: ${spring.application.name}
             uri: lb://business-provider/
             predicates:
               - Path=/api/provider/**
eureka:
   client:
# 是否从其他eureka server 获取注册列表，单server时使用false
      serviceUrl:
         defaultZone: http://xue1:10000/eureka/,http://xue2:10001/eureka/
#fetch-registry: false
   instance:
# 将自己的ip注册到Eureka Server上   如果不配置该属性  则默认为false且表示注册微服务所在操作系统的hostname到Eureka Server
      preferIpAddress: true
#instance-id: ${spring.application.name}:${server.port}
      lease-renewal-interval-in-seconds: 3
# 告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
# 每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
      lease-expiration-duration-in-seconds: 7