server:
   port: 8080
   tomcat:
      max-threads: 100
      uri-encoding: UTF-8
spring:
   redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 1000
      jedis:
         pool:
            #最大链接数量，负数无限制
            max-active: 20
            #最大阻塞数量，负数无限制
            max-wait: -1
            #最大空闲数量
            max-idle: 10
            #最小空闲数量
            min-idle: 0
            