server:
   port: 9000
   tomcat:
      max-threads: 100
      uri-encoding: UTF-8
      
spring:
   application:
      name: business-provider
   datasource:
      url: jdbc:mysql://192.168.197.128:3306/xuejiexiong
      username: root
      password: Xuejie123!
      #driverClassName: com.mysql.jdbc.Driver
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 3
   jpa:
      database: mysql
      show-sql: true
      hibernate:
         ddl-auto : update
         dialect: MySQL5Dialect
      
eureka:
   client:
      # 是否从其他eureka server 获取注册列表，单server时使用false
      #fetch-registry: false
      serviceUrl:
         defaultZone: http://localhost:10000/eureka/
   #instance:
      # 将自己的ip注册到Eureka Server上   如果不配置该属性  则默认为false且表示注册微服务所在操作系统的hostname到Eureka Server
      #preferIpAddress: true
      #instance-id: ${spring.application.name}:${server.port}
      
